### PR TITLE
Fix parsing of gameready

### LINKED ISSUE #9: Lc0 client fails if there is a space in path name
Client ran but would not upload games. Renamed directory from "C:\Users\xxx\Desktop\LC0 Client" to "C:\Users\xxx\Desktop\LC0Client"  (no spaces) and was able to upload games. 

May be caused by this line in lc0_main.go:

parts := strings.Split(*lc0Args, " ")

### PR DESCRIPTION
**Pull request by borg323**
The parsing was done splitting the string on spaces, which obviously failed if there were spaces in the filename. However we know that the path is between "trainingfile" and "gameid" and the moves are after "moves" so is easy to get those parts. Fixes #9.

### CODE REVIEW

File: lc0_main.go [hunk 1]
```diff
@@ -244,19 +244,16 @@ func (c *cmdWrapper) launch(networkPath string, args []string, input bool) {
...
+				if idx1 < 0 || idx2 < 0 || idx3 < 0 {
 					log.Printf("Malformed gameready: %q", line)
 					break
 				}
-				file := parts[2]
-				//gameid := parts[4]
-				//result := parts[8]
-				pgn := convertMovesToPGN(parts[10:])
+				file := line[idx1+13:idx2-1]
+				pgn := convertMovesToPGN(strings.Split(line[idx3+6:len(line)]," "))
```
Comment (jnewlin12345) [inline lc0_main.go]: this is fine, it might be more readable to use a regex
